# MySQL database settings

development:
  adapter: mysql2
  encoding: utf8
  database: daybook_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: daybook_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: daybook
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock